name: Terraform Provisioning
on: 
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  provision:
    name: Provision Azure resources
    runs-on: ubuntu-latest 
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: ls
        run: ls -R
      - name: azure login
        run: |
          az login --service-principal -u ${{ secrets.APP_ID }} -p ${{ secrets.PASSWORD }} --tenant ${{ secrets.TENANT_ID }}
      - name: run terraform
        working-directory: ./terraform
        run: |
          terraform init -input=false
          terraform plan -input=false -out-tfplan
          terraform apply -input=false tfplan
        env:
          TF_VAR_APP_ID: ${{ secrets.APP_ID }}
          TF_VAR_PASSWORD: ${{ secrets.PASSWORD }}
          TF_VAR_RESOURCE_GROUP_NAME: "Joe.Amedeo"
          TF_VAR_REGION: "East US 1"