name: Terraform Provisioning
on: 
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  provision:
    name: Provision Azure resources
    runs-on: ubuntu-latest
    env:
      APP_ID: ${{ secrets.APP_ID }}
      PASSWORD: ${{ secrets.PASSWORD }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SERVICE_PRINCIPAL_NAME: ${{ secrets.SERVICE_PRINCIPAL_NAME }}
      OBJECT_ID: ${{ secrets.OBJECT_ID }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: ls
        run: ls -R
      - name: azure login
        run: |
          az login --service-principal -u $APP_ID -p $PASSWORD --tenant $TENANT_ID
      - name: run terraform
        working-directory: ./terraform
        run: |
          terraform init -input=false
          terraform plan -input=false -out-tfplan
          terraform apply -input=false tfplan
        env:
          TF_VAR_APP_ID: ${{ env.APP_ID }}
          TF_VAR_PASSWORD: ${{ env.PASSWORD }}
          TF_VAR_RESOURCE_GROUP_NAME: "Joe.Amedeo"
          TF_VAR_REGION: "East US 1"