name: Terraform Provisioning
on: 
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  provision:
    name: Provision Azure resources
    runs-on: ubuntu-latest 
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: ls
        run: ls -R
      - name: run terraform
        working-directory: ./terraform
        run: |
          docker run -i hashicorp/terraform:latest init
          docker run -i hashicorp/terraform:latest apply -auto-approve .
        env:
          TF_VAR_APP_ID: ${{ secrets.APP_ID }}
          TF_VAR_PASSWORD: ${{ secrets.PASSWORD }}
          TF_VAR_RESOURCE_GROUP_NAME: "Joe.Amedeo"
          TF_VAR_REGION: "East US 1"